# Usando uma imagem base do Python
FROM python:3.10-slim

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando o arquivo Python ao Diretório de trabalho no container
COPY produtos_esportivos.py .

# Comando para executar o script Python
CMD ["python", "produtos_esportivos.py"]